/* empty css                      */import{a as b,S as L,N as u}from"./assets/vendor-CE1S04ml.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(o){if(o.ep)return;o.ep=!0;const a=n(o);fetch(o.href,a)}})();const w="https://pixabay.com/api/";class P{constructor({apiKey:t,perPage:n=40}){this.apiKey=t,this.perPage=n,this.page=1,this.query="",this.http=b.create({baseURL:w,timeout:15e3,params:{key:this.apiKey,image_type:"photo",orientation:"horizontal",safesearch:!0}})}setQuery(t){this.query=t.trim()}resetPage(){this.page=1}incrementPage(){this.page+=1}async fetchImages(){return this.query?(await this.http.get("",{params:{q:this.query,page:this.page,per_page:this.perPage}})).data:{hits:[],total:0,totalHits:0}}}const r={form:null,queryInput:null,gallery:null,loadMoreBtn:null,loader:null,status:null},s={currentQuery:"",totalHits:0,loadedHits:0},l=new P({apiKey:"51845801-c9cb87929120431e74140b87d",perPage:40});let h=null;document.addEventListener("DOMContentLoaded",()=>{r.form=document.getElementById("search-form"),r.queryInput=document.getElementById("searchQuery"),r.gallery=document.getElementById("gallery"),r.loadMoreBtn=document.getElementById("load-more"),r.loader=document.getElementById("loader"),r.status=document.getElementById("status"),r.form.addEventListener("submit",q),r.loadMoreBtn.addEventListener("click",S),h=new L(".gallery a",{captionsData:"alt",captionDelay:250})});function y(e){r.loader.hidden=!e}function d(e){r.loadMoreBtn.hidden=!e}function f(e){e?(r.status.hidden=!1,r.status.textContent=e):(r.status.hidden=!0,r.status.textContent="")}function B(){r.gallery.innerHTML=""}function H(e){const t=e.map(({webformatURL:n,largeImageURL:c,tags:o,likes:a,views:i,comments:g,downloads:p})=>`
      <li class="photo-card">
        <a href="${c}">
          <img src="${n}" alt="${I(o)}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes</b> ${a}</li>
          <li><b>Views</b> ${i}</li>
          <li><b>Comments</b> ${g}</li>
          <li><b>Downloads</b> ${p}</li>
        </ul>
      </li>`).join("");r.gallery.insertAdjacentHTML("beforeend",t),h.refresh()}function I(e){return String(e).replace(/[&<>"]+/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[t])}async function q(e){e.preventDefault();const t=r.queryInput.value.trim();if(!t){u.Notify.info("Please enter a search term.");return}s.currentQuery=t,s.loadedHits=0,s.totalHits=0,B(),d(!1),f(""),l.setQuery(t),l.resetPage(),await m()}async function S(){await m()}async function m(){try{y(!0);const{hits:e,totalHits:t}=await l.fetchImages();if(l.page===1){if(s.totalHits=t,t===0){u.Notify.failure("Sorry, there are no images matching your search query. Please try again."),d(!1);return}u.Notify.success(`Hooray! We found ${t} images.`)}H(e),s.loadedHits+=e.length,E();const n=s.loadedHits<s.totalHits;d(n),f(n?"":"We're sorry, but you've reached the end of search results."),l.incrementPage()}catch(e){console.error(e),u.Notify.failure("Something went wrong. Please try again later.")}finally{y(!1)}}function E(){const e=r.gallery.querySelector(".photo-card");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
